// PAGES //

import "./pages"
import "./pages/home"
import "./pages/lists"
import "./pages/notes"
import "./pages/newNote"
import "./pages/bills"
import "./pages/tasks"
import "./pages/settings"
import "./pages/settings/activeFridge"
import "./pages/settings/yourFridge"

// COMPONENTS //

import "./components/mainNav"
import "./components/mainNavItem"
import "./components/settingsBar"
import "./components/settingsNavItem"
import "./components/settingsNav"
import "./components/backBar"
import "./components/fridgeNameUpdater"
import "./components/modal"
import "./components/button"
import "./components/inviteFamilyModal"
import "./components/fridgeMembers"
import "./components/fridgeMemberCard"
import "./components/fridgeSelector"
import "./components/fridgeSelectorCard"
import "./components/tabs"
import "./components/newNote/layouts"
import "./components/newNote/editor"
import "./components/notes/style1"
import "./components/notes/style2"
import "./components/notes/style3"


// ICONS //

import "./components/icons/iconHome"
import "./components/icons/iconShoppingCart"
import "./components/icons/iconNote"
import "./components/icons/iconMoney"
import "./components/icons/iconClipboard"
import "./components/icons/iconCog"
import "./components/icons/iconBack"
import "./components/icons/iconSignOut"
import "./components/icons/iconFridge"
import "./components/icons/iconList"
import "./components/icons/iconUsers"
import "./components/icons/iconPlane"
import "./components/icons/iconTrash"
import "./components/icons/iconCheckCircle"
import "./components/icons/iconAdd"
import "./components/icons/iconLayout"
import "./components/icons/iconEye"
